FROM openjdk:11-jdk

#ARG AWS_RDS_URL
#ARG AWS_RDS_USERNAME
#ARG AWS_RDS_PASSWORD
#ARG JWT_SECRET
#ARG KAKAO_CLIENT_ID
#ARG KAKAO_CLIENT_SECRET
#ARG NAVER_CLIENT_ID
#ARG NAVER_CLIENT_SECRET
#ARG NAVER_CLOUD_ACCESS_KEY
#ARG NAVER_CLOUD_BUCKET_NAME
#ARG NAVER_CLOUD_SECRET_KEY
#
#ENV AWS_RDS_URL=$AWS_RDS_URL
#ENV AWS_RDS_USERNAME=$AWS_RDS_USERNAME
#ENV AWS_RDS_PASSWORD=$AWS_RDS_PASSWORD
#ENV JWT_SECRET=$JWT_SECRET
#ENV KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID
#ENV KAKAO_CLIENT_SECRET=$KAKAO_CLIENT_SECRET
#ENV NAVER_CLIENT_ID=$NAVER_CLIENT_ID
#ENV NAVER_CLIENT_SECRET=$NAVER_CLIENT_SECRET
#ENV NAVER_CLOUD_ACCESS_KEY=$NAVER_CLOUD_ACCESS_KEY
#ENV NAVER_CLOUD_BUCKET_NAME=$NAVER_CLOUD_BUCKET_NAME
#ENV NAVER_CLOUD_SECRET_KEY=$NAVER_CLOUD_SECRET_KEY

ARG JAR_FILE=build/libs/opal-youth-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]