spring:
  ## LOCAL DB
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: opal_user
#    url: jdbc:mysql://localhost:3306/opal_db?characterEncoding=UTF-8&serverTimezone=UTC
#    password: opalDbPw1@

    ## RDS DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${AWS_RDS_USERNAME}
    url: ${AWS_RDS_URL}
    password: ${AWS_RDS_PASSWORD}

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  output:
    ansi:
      enabled: always

cloud:
    aws:
      credentials:
        access-key: ${NAVER_CLOUD_ACCESS_KEY}
        secret-key: ${NAVER_CLOUD_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
#        endpoint: https://kr.object.ncloudstorage.com
        bucket: ${NAVER_CLOUD_BUCKET_NAME}

naver-cloud-sms:
  access-key: ${NAVER_CLOUD_ACCESS_KEY}
  secret-key: ${NAVER_CLOUD_SECRET_KEY}
  service-id: ${NAVER_SENS_SERVICE_ID}
  sender-phone: ${NAVER_SENS_PHONE_NUMBER}

jwt:
  secret: ${JWT_SECRET}
